### PR TITLE
fix CLI logic and update tests

### LINKED ISSUE #56: Problems with sending coap ipv6 messages in version 0.6.0+
### Description
problems with sending standard (not dtls) coap ipv6 messages to Contiki-NG node via coap-cli version 0.6.0 and upper

#### Actual behavior
```
debian@beaglebone:~$ coap get coap://[fd00::212:4b00:1cbc:1d51]/node/dtls -p 11223344
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND [fd00::212:4b00:1cbc:1d51]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)  
```
(with coap-cli version 0.5.1 all good - remote node successfully receive the message)

### Affected Versions
0.6.0, 0.6.1, 0.7.0

### LINKED ISSUE #122: Not working anymore after breaking changes in `commander` dependency?
The current version of  `coap-cli`  here on GitHub currently seems to not be working anymore because of breaking API changes to the `commander` module it is built upon. I would try to submit a PR with fixes for this issue soon. It might require changes to the command line interface as well, though.

### PR DESCRIPTION
**Pull request by JKRhb**
As a follow-up to #123 this PR tries to fix the logic of the CLI and to update the test cases after the API in the light of the `commander` changes. There are currently still some issues present which is why I opened this PR as a draft for now. Feel free to already leave some review comments if you like :)

Once this PR is being merged, it will fix #122.

Edit: It now also fixes #56.

### CODE REVIEW

**Comment by gerdemann** [comment]
Can you tell me what other issues exist and maybe fix them?
I have also set up Github Actions, it seems to be working.

**Comment by JKRhb** [comment]
I rebased the PR against `main`, the tests which are not working should now be more visible :)

**Comment by gerdemann** [comment]
Unfortunately, I can't help right now because I don't have time. It would be great if you could take care of it.

**Comment by JKRhb** [comment]
> @JKRhb I published a new Version 0.8.0

Awesome, thank you! :)

**Pull request merged**
